### ISSUE TITLE
Engineering 🧰 The Future II.i.

### ISSUE THREAD

**Issue by Ismael-KG** [Ismael-KG/A-History-of-Research-Ethics#103]
### Title

The Future II.i)
### Elevator Pitch

There are a series of questions that have cropped up and need a professional...
### Tasks
The below, I think, should be done in order.
- [ ] #46 -- This is first because it asks whether the latest yaml is apt and establishes the logic behind `wip: true`, all of which is needed to start migrating legacy stories and stories-in-progress
- [ ] #101 -- This PR can go next, as it tests the new yaml, acknowledges the Yehudis contributions (😄), and does so on a story that is already published. It also possibly raises questions about how netlify shows previews of deployments...
- [ ] #102 -- This is the first PR for the migration of a story-in-progress. If this works, I can continue copying and pasting
- [ ] #98 -- The Final Frontier

### Skills

| Skill | Rationale |
| --- | --- |
| GitHub | Requires knowledge about PRs |
| yaml and markdown | I think these are the languages @yochannah has been using 😅 |
| Netlify | There is currently a problem whereby previews of deployments in PRs lead to an error-404 page |

**Comment by yochannah** [comment]
so for #46 I think it might be ready to go, and then you'll need to pull in stuff from the main branch. It might be the UI can do that but I'm tired and can't remember right now. nudge me if needed, it'll take only 30 seconds.

**Comment by Ismael-KG** [comment]
I'll revise these in the morrow from my laptop — I am excitedly merging stuff from my iPad without checking what any of it looks like 😁

**Comment by Ismael-KG** [comment]
The image is squashy. How do we maintain the height-width ratio with the max-48px width, @yochannah?

![image](https://user-images.githubusercontent.com/64027166/146634969-8b203140-c47b-44a5-af2b-28a6ed8ae165.jpeg)

**Comment by Ismael-KG** [comment]
So @yochannah was on absolute fire today and I am **very very grateful!** It's now time to face some growing pains. What I have found with a `wip: yes` story is that the text knows no boundaries!

![Screenshot 2022-01-03 at 18 00 55](https://user-images.githubusercontent.com/64027166/147963828-3acce41d-228e-45a3-88ff-93ddb15dfb43.png)

I haven't tested 'wip: review` yet, and the [trinary approach](https://github.com/Ismael-KG/An_Incomplete_History_of_Research_Ethics/issues/40#issuecomment-1001559740) might bring up new problems yet!
