### ISSUE TITLE
The Future

### ISSUE THREAD

**Issue by Ismael-KG** [Ismael-KG/A-History-of-Research-Ethics#26]
Tracking significant actions for a "solid" foundation for _The Timeline_:
- [x] Editorial guidelines (relates to #24)
- [x] Create a Protocols.md file to capture the outputs of the above tasks (I use the word "protocols" following [Colouring Cities](https://github.com/colouring-london/colouring-london/issues/690)' lead)
- [x] Citable DOI (see [#25](https://github.com/Ismael-KG/A-History-of-Research-Ethics/issues/25))
- [x] Create a more tailored version of NISO's [CRediT taxonomy](https://credit.niso.org/) for contributor roles) (#27)
- [x] Clarify what "reliable sources" are.
- [x] Create Code_of_Conduct.md
- [x] #28
- [x] Create an issue template for Protocol 3's "Sunday uploads" stage (so there is an issue to be closed whenever new stories are uploaded after pre-publication peer review; see #28 ).
- [x] Create #31 to capture tasks that have not been completed and further developments.

**Comment by Ismael-KG** [comment]
Not sure where the "Sunday Uploads" issue template went. Trying again...

**Comment by Ismael-KG** [comment]
Ah, had missed the big green "propose changes" button!
