### ISSUE TITLE
Engineering 🧰 Migrate to github.io

### ISSUE THREAD

**Issue by Ismael-KG** [Ismael-KG/A-History-of-Research-Ethics#40]
### Title

Migrate to github.io
### Elevator Pitch

Following #37 and #31 , migrate stories to https://ismael-kg.github.io/A-History-of-Research-Ethics/ using the new stories template.
### Justification

This will track changes to stories in light of @yochannah's very helpful yaml code, which is now [here](https://github.com/Ismael-KG/A-History-of-Research-Ethics/blob/79046cb5df2cf1df0211174f4e29ec01f77bb032/A%20Template%20for%20Stories.md).
### Skills

| Skill | Rationale |
| --- | --- |
| Copying & Pasting, and knowing the stories | There is still a chance that some stories to not adhere perfectly to the new yaml-based template, so an eye must be kept on how they integrate |
| Coding & Bug-Fixing | For when errors do appear |

### Tasks
- [x] Migrate Stories
- [x] Review first migrations (see [comment below](https://github.com/Ismael-KG/A-History-of-Research-Ethics/issues/40#issuecomment-988169662))
- [x] Review all migrations of Stories
- [x] Migrate Stories in Progress
- [x] Revisit migrated Stories and relocate to Works_In_Progress where necessary
- [ ] Migrate Published but needs Improving
- [ ] Edit [the template](https://github.com/Ismael-KG/A-History-of-Research-Ethics/blob/ed3bde531f577c3bd77c346c74cd16256dda01c6/A%20Template%20for%20Stories.md) to include instructions (remember to explain that questions/errors can be discussed in PRs, rather than committed directly).
- [x] Add "author element" to yaml (as per [comment](https://github.com/Ismael-KG/A-History-of-Research-Ethics/issues/40#issuecomment-989012021)).
- [ ] Edit story title structure to include mention of "(work in progress)" as per [other comment](https://github.com/Ismael-KG/A-History-of-Research-Ethics/issues/40#issuecomment-990742972) — one for @yochannah's magicologicus.
- [x] Create issues for Stories, so potential contributors can make suggestions

**Comment by Ismael-KG** [comment]
These four early migrations need updating:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/64027166/145085974-ca1e0054-235d-4574-9b70-b4f73e7294b2.png">

**Comment by Ismael-KG** [comment]
@yochannah - just a detail, as I had resigned to this method for GitHub anyway: BCE stories appear in the wrong order:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/64027166/145097945-f815cab8-b0bc-4e6b-aa41-95b28caa96ce.png">

This is [genuinely fine](https://github.com/Ismael-KG/A-History-of-Research-Ethics/issues/1#issuecomment-955179066), but if you know a magic trick to make BCE years appear in the right order, that would be great!

**Comment by yochannah** [comment]
@Ismael-KG like this? #41

**Comment by Ismael-KG** [comment]
@yochannah do you know how to add a new element (author) to the yaml? Under date and category, same format, it would be great to have a line for "author(s)". 

<img width="430" alt="image" src="https://user-images.githubusercontent.com/64027166/145252758-595346cf-e5c5-45cc-97c3-5afa77a3d1f6.png">


There will then be a question as to whether:
* we add different lines for each [contribution type](https://github.com/Ismael-KG/A-History-of-Research-Ethics/blob/main/Protocols.md#protocol-3-contribution-types); or 
* whether the new element is "contributor(s)" and each contributor's name is followed by their contribution type in brackets; or the why-not-both option
* whether there is one line for author(s) and another for contributor(s).

**Comment by Ismael-KG** [comment]
Oh, I know! @yochannah , story titles should end with "(work in progress)" if that is the case!

The reason I haven't migrated most stories is I am not sure what to do with "incomplete" ones. I think a flag like this (by default, include "(work in progress)") would be great! This way, readers know whether to expect much more content in stories >.<

**Comment by yochannah** [comment]
`wip: true` ?

**Comment by Ismael-KG** [comment]
I suppose so! Like this?

```
---
layout: story
title: "title"
wip: true or false
historical-date:
  title: "year, explanation or as per"
  bce: true or false
  year: YYYY
  source: link to the source that justifies the choice of date
  author: surname(s) of authors of the linked source
  source-date: year
category: opening-knowledge, ldf, improving-research or research-tragedies
tags: ["Bioethics", "How We Do Things","Science Influencers","What We Value"]
media:
  source: link to the site where the image is; delete line if there is no image
  caption: "ALT text and acknowledgement of source"; delete line if there is no image
read-more: link to the story's pertinent document/article/book, if there is one; otherwise, delete line
intro: text
---
### The Story
<!-- Paste the story into this line! Remember the old adage: a line is a paragraph, and a blank line must be placed between paragraphs. -->
```

How about the author? Adding a line for "Author(s)" (like "category") didn't work.

**Comment by yochannah** [comment]
add the author line, I'll need to add some logic into the display template
to output it, that's all

**Comment by Ismael-KG** [comment]
Amazing, added wip, authors and contributors:

```
---
layout: story
title: "title"
wip: true or false
historical-date:
  title: "year, explanation or as per"
  bce: true or false
  year: YYYY
  source: link to the source that justifies the choice of date
  author: surname(s) of authors of the linked source
  source-date: year
category: opening-knowledge, ldf, improving-research or research-tragedies
author(s): full name(s)
contributor(s): full name(s) and [contribution type](https://github.com/Ismael-KG/A-History-of-Research-Ethics/blob/main/Protocols.md#Protocol-3-Contribution-Types) between brackets
tags: ["Bioethics", "How We Do Things","Science Influencers","What We Value"]
media:
  source: link to the site where the image is; delete line if there is no image
  caption: "ALT text and acknowledgement of source"; delete line if there is no image
read-more: link to the story's pertinent document/article/book, if there is one; otherwise, delete line
intro: text
---
### The Story
<!-- Paste the story into this line! Remember the old adage: a line is a paragraph, and a blank line must be placed between paragraphs. -->
```

Of course, the contributor line can disappear when necessary, and I won't be putting my name down as author until others write stuff. My name appears in enough places on this already!

**Comment by yochannah** [comment]
ah, so I just upset Jekyll by trying to update the template to support `author(s)` - could we make it `authors` instead?

**Comment by yochannah** [comment]
... oh goodie, I note it's not really implemented yet. I will use authors.

**Comment by Ismael-KG** [comment]
@yochannah, is this how the yaml should look?
```
---
layout: story
title: "title"
wip: true or false
  issue: 
historical-date:
  title: "year, explanation or as per"
  bce: true or false
  year: YYYY
  source: link to the source that justifies the choice of date
  author: surname(s) of authors of the linked source
  source-date: year
category: opening-knowledge, ldf, improving-research or research-tragedies
authors: full name(s)
contributors: full name(s) and [contribution type](https://github.com/Ismael-KG/A-History-of-Research-Ethics/blob/main/Protocols.md#Protocol-3-Contribution-Types) between brackets
tags: ["Bioethics", "How We Do Things","Science Influencers","What We Value"]
media:
  source: link to the site where the image is; delete line if there is no image
  caption: "ALT text and acknowledgement of source"; delete line if there is no image
read-more: link to the story's pertinent document/article/book, if there is one; otherwise, delete line
intro: text
---
### The Story
<!-- Paste the story into this line! Remember the old adage: a line is a paragraph, and a blank line must be placed between paragraphs. -->
```

**Comment by yochannah** [comment]
For now it looks good! I see nothing that frightens me.

**Comment by Ismael-KG** [comment]
@yochannah – new thought on `wip:`

Can it have three values? For each, the following would happen:

`wip: true`
> yaml shows everything + "**If you would like to suggest improvements to this story, please check the [protocols](https://github.com/Ismael-KG/A-History-of-Research-Ethics/blob/main/Protocols.md) for contributors and leave a comment on issue [linked issue number]!**"

`wip: false`
> yaml shows title, year, intro + (a short text I can't currently find but which guides people to the relevant conceptualisation issue"

`wip: review`
> yaml shows title, year, intro + "**This story is almost ready to be published! We would be really grateful if you took a moment to review the current draft, which is here: https://hackmd.io/VW6SvaOYTemXnOd4SMcC4Q?both.**"

**Comment by yochannah** [comment]
trinary sounds great!
